spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:./data/neosquare-local;MODE=MariaDB;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

app:
  seed-demo-data: true
